### ISSUE TITLE
Call to a member function validate() on null

### ISSUE THREAD

**Issue by grekpg** [jgrygierek/SonataBatchEntityImportBundle#20]
admin config 

```
app.admin.shop.admin:
        class: App\Admin\ShopAdmin
        arguments: [ ~, App\Entity\CentroShop, App\Admin\Controller\CentroShopAdminCRUDController ]
```

controller 

```
class CentroShopAdminCRUDController extends MeaSonataCrudController implements ImportControllerInterface
{
    use ImportControllerTrait;
```

where can be a problem ? 

ps. thanks for great bundle...

**Comment by jgrygierek** [comment]
Hi @grekpg , exception happens in line `55` in `BaseImportControllerTrait`?

Validator is injected using CompilerPass for every service with tag `batch_entity_import.controller`. This tag should be automatically added for every class which implements `ImportControllerInterface`. I think that it is not working properly for custom controllers.

As temporary fix you can add tag to your controller:
```
 Your\Namespace\CentroShopAdminCRUDController 
        tags: [ 'batch_entity_import.controller' ]
```

Let me know if this temporary fix works.

I will check it next week and try to fix it.

**Comment by jgrygierek** [comment]
@grekpg can you check if you have autoconfiguration for your services turned on?

```
services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true
```

You can turn it on, or just use the solution from previous post.

**Comment by grekpg** [comment]
> Hi @grekpg , exception happens in line `55` in `BaseImportControllerTrait`?
> 
> Validator is injected using CompilerPass for every service with tag `batch_entity_import.controller`. This tag should be automatically added for every class which implements `ImportControllerInterface`. I think that it is not working properly for custom controllers.
> 
> As temporary fix you can add tag to your controller:
> 
> ```
>  Your\Namespace\CentroShopAdminCRUDController:
>         tags: [ 'batch_entity_import.controller' ]
> ```
> 
> Let me know if this temporary fix works.
> 
> I will check it next week and try to fix it.

When i add

```
    app.admin.controller.centro_shop_admin_crudcontroller:
        class: App\Admin\Controller\CentroShopAdminCRUDController
        public: true
        autowire: true
        autoconfigure: true
        tags:
            - { name: controller.service_arguments }
            - { name: batch_entity_import.controller }
```

error was gone but i get

`JG\BatchEntityImportBundle\Model\Configuration\AbstractImportConfiguration::__construct(): Argument #1 ($em) must be of type Doctrine\ORM\EntityManagerInterface, null given, called in /application/vendor/jgrygierek/batch-entity-import-bundle/src/Controller/BaseImportControllerTrait.php on line 130`

i add 

```
    App\ImportConfiguration\:
        resource: '../src/ImportConfiguration/'
        tags: [ 'controller.service_arguments' ]
        public: true
        autowire: true
        autoconfigure: true
```

import configuration class is

```
class CentroShopImport extends AbstractImportConfiguration
{

    public function getEntityClassName(): string
    {
        return CentroShop::class;

    }

}
```
